# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 19:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('Satara', django.db.models.manager.Manager()),
            ],
        ),
    ]
