# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170813_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(max_length=160),
        ),
    ]
