# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170813_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
    ]
