# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170816_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='retweets',
            field=models.IntegerField(default=''),
        ),
    ]
